rhbase_firewall_allow_services:
  - ssh
  - samba
  - ftp
  - tftp
  - tftp-client

rhbase_user_groups:
  - management
  - technical
  - sales
  - it
  - public


samba_workgroup: AVALON
samba_server_string: 'File server voor Avalon'
samba_netbios_name: 'FILES'
samba_load_homes: true


rhbase_users:
  - name: maarten
    comment: 'Maarten De Smedt'
    groups:
      - public
      - users
      - wheel
      - it
    password: '$6$RFkrtDEm.zSaJo6M$ZgnKyLIWaOL3spMVq0YsK81R452rDuQpKKbphmMwdW71VJbyDA3wrU7lmk2FOAZUros5MEKWFc0roeKW.gok80'
  - name: alexanderd
    comment: 'Alexander De Coninck'
    groups:
      - public
      - technical
    password: '$6$4eGDQ9cmErn7ZXrs$6qs5eqzrhTOiBXUfi4YyNKiFfCMDoAaqPVHPJi8G.87.Qc4iBG1/XpFWvJiaDJFyS.Z1pdynSxa4Xw3U0ZsGu0'
    shell: /sbin/nologin
  - name: stevenh
    comment: 'Steven Hermans'
    groups:
      - public
      - management
    password: '$6$fdfpLFCgzSGwX0ZE$crRTu83.FdFqjhnVg101.DNqGm/LIr3i06SGk4O0R5GhApBck7TppzvAUn.4cG65rj3Hnd3f3hwBqjRMVrSEi1'
    shell: /sbin/nologin
  - name: stevenv
    comment: 'Steven Van Daele'
    groups:
      - public
      - technical
    password: '$6$4q7j0RCXCwv6t0ym$/sS9ACNMJH4vvvwNz0CxcGyi/y/MzDC59vnebu30Yvt4J/u3epbI0VVjZUaLBgCiYzZPUI7PQNK9Fk2JmOmE31'
    shell: /sbin/nologin
  - name: leend
    comment: 'Leen De Meester'
    groups:
      - public
      - technical
    password: '$6$n/Uqa/IY.5yufaxp$XPTaWwjL1x199ye7PMX1CviHCmxeOomx9nxBaYMoecusDGclysKdpPM28NvlzyTVm.pi45GcJwA1BdOSKlaTg.'
    shell: /sbin/nologin
  - name: svena
    comment: 'Sven Aerens'
    groups:
      - public
      - sales
    password: '$6$H/Mmq6Rsk0/Ntj99$jiyUFC4xkbrZtdhF5PNUQ7cfyo0pWQpmIQucEazqH/H7ks9jCINqGvYTmbsCSrGtAzxbFw.3vzglLTQTEHJkf/'
    shell: /sbin/nologin
  - name: nehirb
    comment: 'Nehir Başar'
    groups:
      - public
      - it
    password: '$6$m3pEGJ4TUthiUlmU$6ZwCoTL9diSYs2JDE2pCnwoCOsku2HYWJOQWAfke2.GEfQxjJEZRC1shqvY3JO/k4yQLgO3yQpn0R4TqSQ8IW/'
  - name: krisv
    comment: 'Kris Vanhaverbeke'
    groups:
      - public
      - management
    password: '$6$iqZN.N6nOPOU55KL$S4p/NuAXwIUqeXwNIGnmMs13ZvdmQfpTeoQMAURAWy7QJuYz8axO4rLQZkV5BUPgkrElvpGwXpg29MAUE6GY60'
    shell: /sbin/nologin
  - name: benoitp
    comment: 'Benoit Pluquet'
    groups:
      - public
      - sales
    password: '$6$AOJzOhSC6ih.JVIj$YE4fbJujzUfbHlBFG7VjHRD5nF2PQhfRSJAwM25LDFS0pR/4D322Aj6JZylB0WwWs45cYFWG7cdvTVQtHG/hM0'
    shell: /sbin/nologin
  - name: anc
    comment: 'An Coppens'
    groups:
      - public
      - technical
    password: '$6$Fa1I7PXWEQmaxDtD$TTsSlOqgAJm1B8jOn5s/zxypLJf5ubw6cS6/GZ8KVyebCPbf4OE9oVt/GOtBesqjR6FM58e3DVG7P2taQDJO90'
    shell: /sbin/nologin
  - name: elenaa
    comment: 'Elena Andreev'
    groups:
      - public
      - management
    password: '$6$n5OPm7ZknwmAT0pn$YrFDkOTOUfMnBholf/QMeM.ilu.npXWJTCvuEc4ZMt4QMwrpEYuSxcBTzbIJ9hMdl0aeIyyFx0.tyqkK9Xki4/'
    shell: /sbin/nologin
  - name: evyt
    comment: 'Evy Tilleman'
    groups:
      - public
      - technical
    password: '$6$boNaMhWKEuKiKbNa$meCQpmsCEl7ID0o0/Um.Ty3s28Mm3e0tlxedqNAuipb70FPeYJHiy.g8GgV9Lh477LKOn3g13CYpKAV4Yb93h.'
    shell: /sbin/nologin
  - name: christophev
    comment: 'Christophe Van der Meersche'
    groups:
      - public
      - it
    password: '$6$fNRlC9cjQqICdsA2$/q9bW.9sKgpeNdhBh3zVGULF04TYYYDxyEwMADq0H/0YQ8GvjoS/xFZrFiCxqRGIywzz2WkBOhWE78PQBKSIc0'
  - name: stefaanv
    comment: 'Stefaan Vernimmen'
    groups:
      - public
      - technical
    password: '$6$YF1SJIRvs9oacOvj$jBZXV67E2H9ll7h8VBOmms7mkS61QqRcC.q.ZnJbWUhwgNttBPBOa/.lgYHr9cwU9bLxOYY4zTI1s2oTkoRQC1'
    shell: /sbin/nologin



samba_users:
  - name: maarten
    password: maarten
  - name: alexanderd
    password: alexanderd
  - name : stevenh
    password: stevenh
  - name: stevenv
    password: stevenv
  - name: leend
    password: leend
  - name: svena
    password: svena
  - name: nehirb
    password: nehirb
  - name: krisv
    password: krisv
  - name: benoitp
    password: benoitp
  - name: anc
    password: anc
  - name: elenaa
    password: elenaa
  - name: evyt
    password: evyt
  - name: christophev
    password: christophev
  - name: stefaanv
    password: stefaanv


samba_shares:
  - name: public
    comment: 'Toegan iedere afdeling'
    write_list: +public
    group: public

  - name: management
    comment: 'Share toegankelijk voor mensen uit de afdeling management'
    write_list: +management
    valid_users: +management
    group: management
    directory_mode: '0770'

  - name: technical
    comment: 'Share toegankelijk voor mensen uit de afdeling technical'
    write_list: +technical
    group: technical
    public: yes

  - name: it
    comment: 'Share toegankelijk voor mensen uit de afdeling IT'
    write_list: +it
    valid_users: +it,+management
    group: it
    directory_mode: '0770'

  - name: sales
    comment: 'Share toegankelijk voor mensen uit de afdeling sales'
    write_list: +sales
    valid_users: +management,+sales
    group: sales
    directory_mode: '0770'



vsftpd_anonymous_enable: false
vsftpd_local_enable: true

vsftpd_local_root: /srv/shares
