rhbase_firewall_allow_services:
  - http
  - https
  - ssh

mariadb_databases:
  - name: wordpress
mariadb_users:
  - name: maarten
    password: letmein
    priv: wordpress.*:ALL
    state: present
mariadb_root_password: letmein

#word
wordpress_database: wordpress
wordpress_user: maarten
wordpress_password: letmein

#cert
httpd_SSLCertificateFile: '/etc/pki/tls/certs/newcert.crt'
httpd_SSLCertificateKeyFile: '/etc/pki/tls/private/newkey.key'
httpd_scripting: 'php'
