rhbase_firewall_allow_services:
  - ssh
  - dns
  - https
  - http


bind_zone_name: avalon.lan

bind_zone_master_server_ip: 192.0.2.10
bind_zone_networks:
  - '192.0.2'
  - '172.16'

bind_listen_ipv4:
  - '127.0.0.1'
  - '192.0.2.10'

bind_zone_name_servers:
  - pu001
  - pu002

bind_acls:
  - name: slaves
    match_list:
      - 192.0.2.11

bind_recursion: false

bind_allow_query:
  - 'any'

bind_zone_hosts:
  ## Router
  - name: r001
    ip:
      - 192.0.2.254
      - 172.16.255.254
    aliases:
      - gw
  ## Publiek
  - name: pu001
    ip: 192.0.2.10
    aliases:
      - ns1
  - name: pu002
    ip: 192.0.2.11
    aliases:
      - ns2
  - name: pu003
    ip: 192.0.2.20
    aliases:
      - mail
  - name: pu004
    ip: 192.0.2.50
    aliases:
      - www
  ## Privaat
  - name: pr001
    ip: 172.16.0.1
    aliases:
      - dhcp
  - name: pr002
    ip: 172.16.0.2
    aliases:
      - directory
  - name: pr010
    ip: 172.16.0.10
    aliases:
      - inside
  - name: pr011
    ip: 172.16.0.11
    aliases:
      - files

# Mail server
bind_zone_mail_servers:
  - name: pu003
    preference: 10
