# site.yml
---
  ##lamp
- hosts: pu004
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress
  pre_tasks:
    - name: Copy new key
      copy:
        src: keycert/newkey.key
        dest: /etc/pki/tls/private/newkey.key
    - name: Copy new cert
      copy:
        src: keycert/newcert.crt
        dest: /etc/pki/tls/certs/newcert.crt
#dns
- hosts: pu001,pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
#fileshare
- hosts: pr011
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd
  post_tasks:
    - name: ACL sales
      acl:
        path: /srv/shares/sales
        entity: management
        etype: group
        permissions: rx
        state: present
    - name: ACL it
      acl:
        path: /srv/shares/it
        entity: management
        etype: group
        permissions: rx
        state: present
    - name: ACL technical
      acl:
        path: /srv/shares/technical
        entity: public
        etype: group
        permissions: rx
        state: present
#DHCP
- hosts: pr001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp
